/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador;

import javax.swing.JOptionPane;
import dao.AutomovelDAO;
import java.util.List;
import javax.swing.ImageIcon;
import modelo.Automovel;

/**
 *
 * @author KillerCoffeBR
 */
public class AutomovelTela extends javax.swing.JFrame {

    /**
     * Creates new form Automovel
     */
    private List<Automovel> lista;
    private List<Automovel> lista2;
    Integer posicao;

    public void Limpar() {
        txt_Ano.setText("");
        txt_Cor.setText("");
        txt_Cpf.setText("");
        txt_Id.setText("");
        txt_Modelo.setText("");
        txt_Placa.setText("");
    }

    public void Atualizar() {
        AutomovelDAO dao = new AutomovelDAO();

        lista = dao.listar();
        lista2 = dao.listar();
        posicao = 0;
    }
    
    public AutomovelTela() {

        //Altera o icone no topo da janela
        this.setIconImage(new ImageIcon(getClass().getResource("/icones/car.png")).getImage());

        
        String id = null;
        initComponents();

        AutomovelDAO dao = new AutomovelDAO();
        String cpf = null;

        lista = dao.listarporcpf(cpf);
        lista2 = dao.listarporid(WIDTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnExcluir = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnLimpar = new javax.swing.JButton();
        BtnBuscarId = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Cpf = new javax.swing.JTextField();
        txt_Modelo = new javax.swing.JTextField();
        txt_Cor = new javax.swing.JTextField();
        txt_Placa = new javax.swing.JTextField();
        txt_Ano = new javax.swing.JTextField();
        txt_Id = new javax.swing.JTextField();
        fundo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROParking - Automovel");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/excluir.png"))); // NOI18N
        BtnExcluir.setBorderPainted(false);
        BtnExcluir.setContentAreaFilled(false);
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(BtnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 70, 70));

        BtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        BtnPesquisar.setBorderPainted(false);
        BtnPesquisar.setContentAreaFilled(false);
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 187, 70, -1));

        BtnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/aceitar.png"))); // NOI18N
        BtnSalvar.setBorderPainted(false);
        BtnSalvar.setContentAreaFilled(false);
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 70, 70));

        BtnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo.png"))); // NOI18N
        BtnLimpar.setBorder(null);
        BtnLimpar.setBorderPainted(false);
        BtnLimpar.setContentAreaFilled(false);
        BtnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(BtnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 80, 70));

        BtnBuscarId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/renomear.png"))); // NOI18N
        BtnBuscarId.setBorder(null);
        BtnBuscarId.setBorderPainted(false);
        BtnBuscarId.setContentAreaFilled(false);
        BtnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarIdActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Klavika Regular", 0, 18)); // NOI18N
        jLabel1.setText("CPF:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 53, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Placa:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 53, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Modelo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 79, 28));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cor:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 53, 28));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Id:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 53, 28));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ano:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 53, 28));

        txt_Cpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_Cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CpfActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 155, -1));
        jPanel1.add(txt_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 155, -1));
        jPanel1.add(txt_Cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 155, -1));
        jPanel1.add(txt_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 155, -1));
        jPanel1.add(txt_Ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 155, -1));
        jPanel1.add(txt_Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 155, -1));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lexus.png"))); // NOI18N
        fundo.setToolTipText("");
        jPanel1.add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 270));

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));

        jLabel7.setText("SALVAR                    PESQUISAR CPF          EXCLUIR                    LIMPAR              PESQUISAR ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CpfActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        {

            Automovel automovel = new Automovel();

            if (txt_Placa.getText().isEmpty() || txt_Cpf.getText().isEmpty() || txt_Modelo.getText().isEmpty() || txt_Cor.getText().isEmpty() || txt_Ano.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Preencher todos os campos!");
            } else {
                automovel.setCpf(txt_Cpf.getText());
                automovel.setPlaca(txt_Placa.getText());
                automovel.setModelo(txt_Modelo.getText());
                automovel.setCor(txt_Cor.getText());
                automovel.setAno(Integer.parseInt(txt_Ano.getText()));

                AutomovelDAO dao = new AutomovelDAO();
                Boolean deucerto = dao.inserir(automovel);

                if (deucerto == true) {
                    JOptionPane.showMessageDialog(rootPane, "Veículo cadastrado com sucesso");
                    txt_Ano.setText("");
                    txt_Cor.setText("");
                    txt_Cpf.setText("");
                    txt_Id.setText("");
                    txt_Modelo.setText("");
                    txt_Placa.setText("");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar Veículo!");
                }
                Atualizar();
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed

            Atualizar();
        
        if (txt_Cpf.getText().isEmpty()) {

            Boolean encontrou = false;
            Integer posicaoachou = 0;

            for (Automovel lista1 : lista) {
                if (txt_Cpf.getText().equals(lista1.getCpf())) {
                    encontrou = true;

                    JOptionPane.showMessageDialog(null, "Exibindo automóvel, um momento!");

                    txt_Placa.setText(lista1.getPlaca());
                    txt_Modelo.setText(lista1.getModelo());
                    txt_Cor.setText(lista1.getCor());
                    txt_Ano.setText(lista1.getAno().toString());
                    txt_Ano.setText(lista1.getAno().toString());
                    txt_Cpf.setText(lista1.getCpf().toString());
                    txt_Id.setText(lista1.getId().toString());

                    break;
                }

            }

            if (encontrou == false) {
                JOptionPane.showMessageDialog(null, "Automovel ainda não cadastrado!");
            }

        } else {
            String cpf = txt_Cpf.getText();
            automovelListar autotela;
            autotela = new automovelListar(cpf);
            autotela.setVisible(true);
            autotela.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }

    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        if (txt_Cpf.getText().isEmpty() == false) {
            //instanciando a classe de acesso a dados JogadorDAO       
            AutomovelDAO dao = new AutomovelDAO();

            //chamo o inserir
            boolean deucerto = dao.remover(lista.get(posicao));

            if (deucerto == true) {
                JOptionPane.showMessageDialog(rootPane, "Excluído com sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
            }
            String cpf = null;
            lista = dao.listarporcpf(cpf);
            Limpar();
        } else {

        }
        Atualizar();
    }//GEN-LAST:event_BtnExcluirActionPerformed

    private void BtnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLimparActionPerformed
        Limpar();
        JOptionPane.showMessageDialog(rootPane, "A tela foi limpa com sucesso!");
    }//GEN-LAST:event_BtnLimparActionPerformed

    private void BtnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarIdActionPerformed

        if (!txt_Id.getText().isEmpty()) {

            Boolean encontrou = false;
            Integer posicaoachou = 0;

            for (Automovel lista2 : lista) {
                if (Integer.parseInt(txt_Id.getText()) == lista2.getId()) {
                    encontrou = true;

                    JOptionPane.showMessageDialog(null, "Exibindo automóvel, um momento!");

                    txt_Placa.setText(lista2.getPlaca());
                    txt_Modelo.setText(lista2.getModelo());
                    txt_Cor.setText(lista2.getCor());
                    txt_Ano.setText(lista2.getAno().toString());
                    txt_Ano.setText(lista2.getAno().toString());
                    txt_Cpf.setText(lista2.getCpf().toString());
                    txt_Id.setText(lista2.getId().toString());

                    break;
                }

            }

            if (encontrou == false) {
                JOptionPane.showMessageDialog(null, "Automovel ainda não cadastrado!");
            }

        }
    }//GEN-LAST:event_BtnBuscarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutomovelTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutomovelTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutomovelTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutomovelTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutomovelTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarId;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnLimpar;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_Ano;
    private javax.swing.JTextField txt_Cor;
    private javax.swing.JTextField txt_Cpf;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Modelo;
    private javax.swing.JTextField txt_Placa;
    // End of variables declaration//GEN-END:variables
}
